import { router /*, sendEmail*/ } from '../utils'
import { Request, Response } from 'express'
import { Invoice } from '../entities/Invoice'
import { authorization } from '../middleware/auth'
import { getConnection, Brackets } from 'typeorm'
import { validateInvoice } from '../validations'
import { __Order__ } from '../models/__Order__'
import { __Item__ } from '../models/__Item__'
import { isEmpty } from '../validations/isEmpty'
